augmentation:
  abs_stats:
  - -16.7
  - 7
  probs:
  - 0.3
  - 0.7
  rel_stats:
  - 2.78
  - 4
conf_file: conf/train.yml
data:
  chime6_root: /home/getsum/data/DIHARD3/preprocess
  custom_json_folder: null
  fs: 16000
  label_train: /home/getsum/data/DIHARD3/labels/train
  label_val: /home/getsum/data/DIHARD3/labels/dev
  n_classes: 3
  segment: 500
fbank_kaldi:
  dither: 1.0e-08
  high_freq: -400
  low_freq: 80
  num_mel_bins: 80
  sample_frequency: 16000
  use_energy: false
feats:
  hop_size: 0.01
  inject_noise: false
  layer: 3
  n_feats: 80
  type: wavlm
gpus: '0'
labels:
  collar_ph: 0.0
  merge_ph: 0.0
  merge_vad: 0.0
log_dir: exp/tcn
loss:
  contrast:
    base_temperature: 0.07
    contrast_mode: all
    gamma: 0.01
    temperature: 0.07
mels:
  hop_length: 160
  n_fft: 400
  n_mels: 40
  win_length: 400
mfcc:
  log_mels: true
  n_mfcc: 40
  sample_rate: 16000
mfcc_kaldi:
  dither: 0.0
  high_freq: -400
  low_freq: 40
  num_ceps: 80
  num_mel_bins: 80
  sample_frequency: 16000
  use_energy: false
model: tcn
opt:
  lr: 0.00015
  weight_decay: 1.0e-05
spectrogram_kaldi:
  dither: 0.0
  sample_frequency: 16000
task: count
training:
  accumulate_batches: 1
  batch_size: 16
  gradient_clip: 5
  n_epochs: 200
  num_workers: 16
  resume_from: exp/tcn/checkpoints/epoch=24-step=60650-layer3.ckpt
